'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Student
    Public Property ID As Integer
    Public Property Name As String
    Public Property Age As Integer
    Public Property Address As String
    Public Property PhoneNumber As String

End Class
